### ISSUE TITLE
如何录制游戏的屏幕操作事件？尤其是带有虚拟摇杆的RPG游戏？

### ISSUE THREAD

**Issue by CallMeZack** [NetEase/AutomatorX#63]
你好，想问一下带有虚拟摇杆的RPG游戏的屏幕操作事件（拖拽--不是简单的直线拖拽）如何录制呢？
现在很多RPG游戏都有虚拟摇杆，这种虚拟摇杆的操作事件如何编写脚本/录制呢？

**Comment by codeskyblue** [comment]
说明下是android还是ios，最好能截图举例下，如果是网易内部的，直接popo

**Comment by CallMeZack** [comment]
就是目前市面上随便一款ARPG游戏，不都是有虚拟摇杆嘛，比如，太极熊猫、功夫熊猫等等。安卓。就是这种有虚拟摇杆的，虚拟摇杆的操作如何编写脚本/录制脚本？也就是说怎么写一段脚本来实现虚拟摇杆的功能呢？

**Comment by codeskyblue** [comment]
其实也就是找到需要点的摇杆的位置，然后 long_click

**Comment by codeskyblue** [comment]
不回复我就关闭了
